export const ROUTES = {
  HOME: "/",
  CARTA: "/carta",
  CARRITO: "/carrito",
  CHECKOUT: "/checkout",
  LOGIN: "/login",
  REGISTRO: "/registro",
  MI_CUENTA: "/mi-cuenta",
  MIS_PEDIDOS: "/mi-cuenta/pedidos",
  FIDELIDAD: "/fidelidad",
  COMO_FUNCIONA: "/como-funciona",
  CONTACTO: "/contacto",
  NOSOTROS: "/nosotros",
  PRODUCTO: (slug: string) => `/producto/${slug}`,
  PEDIDO: (id: string) => `/pedido/${id}`,
  ADMIN: "/admin",
  ADMIN_PEDIDOS: "/admin/pedidos",
  ADMIN_PRODUCTOS: "/admin/productos",
  ADMIN_CLIENTES: "/admin/clientes",
  ADMIN_CONFIG: "/admin/configuracion",
  ADMIN_PEDIDO: (id: string) => `/admin/pedidos/${id}`,
  ADMIN_PRODUCTO: (id: string) => `/admin/productos/${id}`,
} as const;
